[package]
name = "cim-implementation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
cgmath = "0.18.0"
chumsky = "1.0.0-alpha.2"
itertools = "0.10.5"
ndarray = "0.15.6"
