[package]
name = "cim-implementation"
version = "0.1.0"
edition = "2021"
default-run = "cim-implementation"

[dependencies]
anyhow = "1.0.69"
cgmath = "0.18.0"
chumsky = "1.0.0-alpha.2"
clap = { version = "4.1.8", features = ["derive"] }
itertools = "0.10.5"
nannou = "0.18.1"
ndarray = "0.15.6"
